# Generated by Django 5.2.12 on 2026-04-06 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FinancialRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Transaction amount (positive number)",
                        max_digits=12,
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("income", "Income"), ("expense", "Expense")],
                        help_text="Type of transaction: income or expense",
                        max_length=10,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("salary", "Salary"),
                            ("freelance", "Freelance"),
                            ("investment", "Investment"),
                            ("food", "Food & Dining"),
                            ("transport", "Transportation"),
                            ("utilities", "Utilities"),
                            ("entertainment", "Entertainment"),
                            ("healthcare", "Healthcare"),
                            ("education", "Education"),
                            ("shopping", "Shopping"),
                            ("rent", "Rent"),
                            ("other", "Other"),
                        ],
                        help_text="Category of the transaction",
                        max_length=20,
                    ),
                ),
                ("date", models.DateField(help_text="Date of the transaction")),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Optional notes about this transaction",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False,
                        help_text="Soft-deleted records are hidden but not removed from database",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-date", "-created_at"],
            },
        ),
    ]
